SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `#__jtax_impot` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `asset_id` INT(10) unsigned NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
    `deduction` TINYINT(1) NOT NULL DEFAULT 1,
    `dons` INT(64) NOT NULL DEFAULT 0,
    `fraisreels` INT(64) NOT NULL DEFAULT 0,
    `impot` VARCHAR(255) NULL DEFAULT '',
    `name` VARCHAR(255) NULL DEFAULT '',
    `nbparts` FLOAT(7) NOT NULL DEFAULT 1,
    `pel` INT(64) NOT NULL DEFAULT 0,
    `revenu` INT(64) NOT NULL DEFAULT 0,
    `year` INT(64) NOT NULL DEFAULT 0,
    `params` TEXT NULL,
    `published` TINYINT(3) NULL DEFAULT 1,
    `created_by` INT unsigned NULL,
    `modified_by` INT unsigned,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `modified` DATETIME,
    `checked_out` int unsigned,
    `checked_out_time` DATETIME,
    `version` INT(10) unsigned NULL DEFAULT 1,
    `hits` INT(10) unsigned NULL DEFAULT 0,
    `access` INT(10) unsigned NULL DEFAULT 0,
    `ordering` INT(11) NULL DEFAULT 0,
    PRIMARY KEY  (`id`),
    KEY `idx_name` (`name`),
    KEY `idx_year` (`year`),
    KEY `idx_access` (`access`),
    KEY `idx_checkout` (`checked_out`),
    KEY `idx_createdby` (`created_by`),
    KEY `idx_modifiedby` (`modified_by`),
    KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `#__jtax_year` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `asset_id` INT(10) unsigned NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
    `name` VARCHAR(255) NULL DEFAULT '',
    `taux1` FLOAT(7) NOT NULL DEFAULT 0,
    `taux2` FLOAT(7) NOT NULL DEFAULT 0,
    `taux3` FLOAT(7) NOT NULL DEFAULT 0,
    `taux4` FLOAT(7) NOT NULL DEFAULT 0,
    `tranche1` INT(64) NOT NULL DEFAULT 0,
    `tranche2` INT(64) NOT NULL DEFAULT 0,
    `tranche3` INT(64) NOT NULL DEFAULT 0,
    `tranche4` INT(64) NOT NULL DEFAULT 0,
    `params` TEXT NULL,
    `published` TINYINT(3) NULL DEFAULT 1,
    `created_by` INT unsigned NULL,
    `modified_by` INT unsigned,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `modified` DATETIME,
    `checked_out` int unsigned,
    `checked_out_time` DATETIME,
    `version` INT(10) unsigned NULL DEFAULT 1,
    `hits` INT(10) unsigned NULL DEFAULT 0,
    `access` INT(10) unsigned NULL DEFAULT 0,
    `ordering` INT(11) NULL DEFAULT 0,
    PRIMARY KEY  (`id`),
    KEY `idx_name` (`name`),
    KEY `idx_access` (`access`),
    KEY `idx_checkout` (`checked_out`),
    KEY `idx_createdby` (`created_by`),
    KEY `idx_modifiedby` (`modified_by`),
    KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;


